### ISSUE TITLE
Variable undefined issue in pform.f

### ISSUE THREAD

**Issue by keweili** [sanjayg0/feappv#2]
When compiling the FEAPpv source code for the x86 platform, my student chose the "integer4" folder under the "include" folder, then we got an error saying the variables "ht1", "ht2", and "ht3" are undefined in the subroutine "pform.f". Thus, I think the file "hdata.h" should be defined as follows so that we have those three variables. 

```
integer           nh1,nh2,nh3,ht1,ht2,ht3                     !int 4
common /hdata/    nh1,nh2,nh3,ht1,ht2,ht3
```

See also https://github.com/keweili/feappv/blob/master/include/integer4/hdata.h

With this change, the 32-bit executable file worked on my machine.

**Comment by sanjayg0** [comment]
Ooops.  I've fixed the error.  We have debated deleting integer4 altogether but have not yet made a decision.  Would it not be rare for anyone (compiling code) to still be working on a 32-bit only machine?

**Comment by keweili** [comment]
My student had a 64-bit machine, but somehow she chose to compile the code for the x86 (Win32) platform in Visual Studio (Maybe that is the default option). Then, we found this error. After the change, it worked well, so I would keep the folder.

**Comment by sanjayg0** [comment]
fyi. i put the bug fix on both the master and the devel branches.

-------------------------------------------------------------------
Sanjay Govindjee, PhD, PE
Horace, Dorothy, and Katherine Johnson Professor in Engineering

779 Davis Hall
University of California
Berkeley, CA 94720-1710

Voice:  +1 510 642 6060
FAX:    +1 510 643 5264
s_g@berkeley.edu
http://faculty.ce.berkeley.edu/sanjay
-------------------------------------------------------------------

Books:

Engineering Mechanics of Deformable Solids
http://amzn.com/0199651647

Engineering Mechanics 3 (Dynamics) 2nd Edition
http://amzn.com/3642537111

Engineering Mechanics 3, Supplementary Problems: Dynamics
http://www.amzn.com/B00SOXN8JU

NSF NHERI SimCenter
https://simcenter.designsafe-ci.org/
-------------------------------------------------------------------
