### ISSUE TITLE
Variable type mismatch in blkgen.f

### ISSUE THREAD

**Issue by keweili** [sanjayg0/feappv#3]
Hi, when I was compiling this version of FEAPpv on another computer, and there is an error in the file /program/blkgen.f.  The variable "td(15)" is declared as a "real*8" type on line 43 , and then it is passed as the first argument to the subroutine ublk() near line 350. However, the first argument in that subroutine is declared as an "integer" on 47 line of /user/ublk.f. Plesae check and advise.

**Comment by sanjayg0** [comment]
This a typo in version 4.1.   It has been fixed on the devel branch.  You just need to remove the argument td on the calling line.  I'll update master branch on git in a minute.
