### ISSUE TITLE
Capabilities of Feappv

### ISSUE THREAD

**Issue by JAMMIASHOK** [sanjayg0/feappv#5]
Dear sir,
Thank you for hosting Feappv on GIthub !
I Have gone through the webpage of Feappv and Feap. What are the current capabilities of Feappv ? 
The document on the webpage says it's old. Currently what are it's capabilities ? It is possible to extend the capabilities as an 
opensource collaboration. Right now there are not much robust FEM libraries written Fortran. Does Feappv has a good potential for extension ? Just a quick browsing through the program folders shows that it's highly modular and can be extended. Now Fortran language also has developed so much - Object Orientation, C - interopability... almost on par with c++ (has a new website - https://fortran-lang.org/). Kindly let me know.

**Comment by sanjayg0** [comment]
Please place such question on the FEAP user forum (sub-board for FEAPpv):  http://feap.berkeley.edu
