### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by Konstantin8105** [sanjayg0/feappv#7]
Could you clarify the license of code? MIT, BSD, ...

**Comment by sanjayg0** [comment]
Good question.  FEAP and by extension FEAPpv pre-date modern software licensing systems.   All the routines are copyrighted but that does not tell you too much about the licensing details.  Let me check with the licensing office on how they view the situation.

**Comment by sanjayg0** [comment]
It has been determined that the appropriate license for FEAPpv is the BSD-3 license.  The master and devel branches now contain the a license file (LICENSE.txt).
